### ISSUE TITLE
Fail: Orphan format specifier: %E

### ISSUE THREAD

**Issue by yannick** [dhasenan/urld#15]
i'm getting `Task terminated with unhandled exception: Orphan format specifier: %E` for certain urls

**Comment by dhasenan** [comment]
Unfortunately, without a stacktrace or a test case, I can't do much here.

Are you calling `logf` or `writef` with a URL as the first parameter?

**Comment by dhasenan** [comment]
That exception message only comes from std.format.format.

There are several usages of std.format.format in urld:

line 1281: `format("%%%02X", b)`

line 1419:

```D
			throw new URLException(
					format(
						"domain name '%s' contains illegal character '%s' at position %s",
						unicodeHostname, d, i));
```

And several uses in unittests. None of them use the `%E` format specifier.

std.stdio isn't used. Neither is std.experimental.logger.

You are probably using a `logf` or `writef` family function and passing a URL as the first parameter (or concatenating a URL to a string). The URL contains characters that are percent-encoded. Use the `log` or `write` equivalent, or use an explicit format string.

It's not a good idea in general to pass anything but a string literal as the format parameter of a format function.

**Comment by yannick** [comment]
u sorry,filled that in a rush. i was calling `parseURL`
so my guess is that certain legal tokes ( %E ?) can cause an exception.
if that doesn't make any sense directly i could try to find the culprit.

**Comment by dhasenan** [comment]
Can you give me a stacktrace, the string that caused the problem, or the
exact line of code in situ? Without that, I can't help you.

I assumed you were calling parseURL, but if you're then passing that parsed
URL as the first argument to `writef` or `logf`, it will implicitly convert
it to a string and then treat that as a format string, which would produce
exactly the type of error you encountered here.
