### ISSUE TITLE
why alias toString this

### ISSUE THREAD

**Issue by FraMecca** [dhasenan/urld#16]
Why is the URL type implicitely converted to string?
It makes it a pain to pass the structure around and it needs to be converted back many times.

**Comment by dhasenan** [comment]
The alias this is to make URL more of a drop-in replacement for APIs expecting a string.

Do you have any examples of where this is causing issues? It should only convert to string when you store/pass it as `string` explicitly. If passing a URL prefers a `string` overload to a `URL` overload, that sounds like a DMD bug.

**Comment by FraMecca** [comment]
It was an error on my side. Sorry for the inconvenience.
