### ISSUE TITLE
Arrays in query striings

### ISSUE THREAD

**Issue by anton-dutov** [dhasenan/urld#6]
AFAIK rfc allows dublicate keys in query string
?key=foo&key=bar

where operator[] takes last (or first?) element
and some method e.g. allValues() takes values as array of strings

Please look at element (URIQuery) And followed discussion
https://github.com/D-Programming-Language/phobos/pull/2258/files#diff-90295df2260451b844d49e3e76d04369R1057

You have nice try and may be can simplify that

**Comment by dhasenan** [comment]
Fixed in 0.5.0. Sorry I didn't mention it when 0.5.0 was released.
