### ISSUE TITLE
Port number 0

### ISSUE THREAD

**Issue by belka-ew** [dhasenan/urld#7]
Use 0 if the port is unknown isn't very good imho since port 0 can exist and is reserved for both, TCP and UDP. See IANA: http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml
So I can't distinguish between host/ and host:0/. Maybe use int for port number and a negative number if the port is unknown. Or even better use a boolean (portProvided) that keeps if the port was set or not? The boolean would also eliminate the need of providedPort, since you can just check this boolean to see if the port was explicitly provided by the user.

**Comment by dhasenan** [comment]
Port 0 is reserved, has no assigned service, has a dead maintainer, and can't be listened on in Windows, Linux, BSD, or OpenVMS. I've heard rumors that BSD rejects incoming packets with source port 0.

Do you know of a system that allows you to listen on this port?

**Comment by belka-ew** [comment]
It seems 0 is reserved, but used everywhere for internal purposes and as a real port. You're right. I just thought about a theoretically idealistic implementation of all protocols.
I worked today with your library and have some questions, but I don't want to open an issue only for questions, so if you don't mind I ask it here.

I'm need some URL parsing but in more general way. I'll mention also some use cases, why it could be useful for some people

- For example pure splitting the URL into the parts (protocol, user, password, host and so on) but without encoding and without parsing the request query. Use case: I'm testing a web server and I want to create some fake variables from a given URL. For example I get an URL and want only set HTTP variables like REQUEST_URI, QUERY_STRING without parsing their content.
- Parsing the query string only. Use case: I'm writing a web server and it gets from the browser or another server QUERY_STRING. So there is no need to parse the URL but only the query string.
- Some useful stuff for decoding/encoding parts of the URL like encodeComponent/decodeComponent in Phobos. You accomplish this with url.split("/"), then encode and then join again somewhere in your code but it could be useful as a separate function.

So I just thought it could be nice to have smaller functions that are more general. Maybe move some functionality in separate functions or add some additional functions. 
There were some other small things, where I could think of another implementation way, but it isn't that important; maybe I just don't see something or you have different use cases.

Sorry for the long message, I hope I could explain it. Is it something you would be interested in, something could be done?
